export const STRINGS = {
  en: {
    select: 'Select',
    hand: 'Hand',
    erase: 'Erase',
    exportPng: 'Export PNG',
    copyImage: 'Copy image',
    exportSvg: 'Export SVG',
    editDelete: 'Delete',
    editCopy: 'Copy',
    editCut: 'Cut',
    grid: 'Grid',
    gridShow: 'Show grid',
    gridLines: 'Lines',
    gridDots: 'Dots',
    on: 'on',
    off: 'off',
    pen: 'Pen',
    rectangle: 'Rectangle',
    ellipse: 'Ellipse',
    line: 'Line',
    arrow: 'Arrow',
    text: 'Text',
    image: 'Image',
    laser: 'Laser',
    menu: 'Menu',
    styleStroke: 'Stroke',
    styleFill: 'Fill',
    styleTextColor: 'Text',
    styleNoFill: 'No fill',
    stylePanelSelection: 'Selection',
  },
  tr: {
    select: 'Sec',
    hand: 'El',
    erase: 'Sil',
    exportPng: 'PNG olarak kaydet',
    copyImage: 'Gorseli kopyala',
    exportSvg: 'SVG olarak kaydet',
    editDelete: 'Sil',
    editCopy: 'Kopyala',
    editCut: 'Kes',
    grid: 'Izgara',
    gridShow: 'Izgarayi goster',
    gridLines: 'Cizgiler',
    gridDots: 'Noktalar',
    on: 'acik',
    off: 'kapali',
    pen: 'Kalem',
    rectangle: 'Dikdortgen',
    ellipse: 'Elips',
    line: 'Cizgi',
    arrow: 'Ok',
    text: 'Metin',
    image: 'Resim',
    laser: 'Lazer',
    menu: 'Menu',
    styleStroke: 'Cizgi',
    styleFill: 'Doldur',
    styleTextColor: 'Metin',
    styleNoFill: 'Doldurma',
    stylePanelSelection: 'Secim',
  },
  ja: {
    select: '選択',
    hand: '手のひら',
    erase: '消去',
    exportPng: 'PNGを書き出す',
    copyImage: '画像をコピー',
    exportSvg: 'SVGを書き出す',
    editDelete: '削除',
    editCopy: 'コピー',
    editCut: '切り取り',
    grid: 'グリッド',
    gridShow: 'グリッドを表示',
    gridLines: '線',
    gridDots: '点',
    on: 'オン',
    off: 'オフ',
    pen: 'ペン',
    rectangle: '矩形',
    ellipse: '楕円',
    line: '線',
    arrow: '矢印',
    text: 'テキスト',
    image: '画像',
    laser: 'レーザー',
    menu: 'メニュー',
    styleStroke: '線の色',
    styleFill: '塗り',
    styleTextColor: 'テキスト',
    styleNoFill: '塗りなし',
    stylePanelSelection: '選択',
  },
} as const
