export const STRINGS = {
  en: {
    select: 'Select',
    hand: 'Hand',
    erase: 'Erase',
    exportPng: 'Export PNG',
    grid: 'Grid',
    gridShow: 'Show grid',
    gridLines: 'Lines',
    gridDots: 'Dots',
    on: 'on',
    off: 'off',
    pen: 'Pen',
    rectangle: 'Rectangle',
    ellipse: 'Ellipse',
    line: 'Line',
    arrow: 'Arrow',
    text: 'Text',
    image: 'Image',
    laser: 'Laser',
    menu: 'Menu',
  },
  tr: {
    select: 'Sec',
    hand: 'El',
    erase: 'Sil',
    exportPng: 'PNG olarak kaydet',
    grid: 'Izgara',
    gridShow: 'Izgarayi goster',
    gridLines: 'Cizgiler',
    gridDots: 'Noktalar',
    on: 'acik',
    off: 'kapali',
    pen: 'Kalem',
    rectangle: 'Dikdortgen',
    ellipse: 'Elips',
    line: 'Cizgi',
    arrow: 'Ok',
    text: 'Metin',
    image: 'Resim',
    laser: 'Lazer',
    menu: 'Menu',
  },
} as const
